require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'startWithBack4app' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'startWithBack4appTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
  # ^commented out per solution from stack overflow
  # https://stackoverflow.com/questions/66019068/event2-event-config-h-file-not-found/66055723
end

target 'startWithBack4app-tvOS' do
  # Pods for startWithBack4app-tvOS

  target 'startWithBack4app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
